header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: DataSage
    content: |
      SPDX-License-Identifier: Apache-2.0
  paths:
    - "**/*.go"
    - "**/*.sh"
    - "**/Dockerfile"
    - "**/Makefile"

  paths-ignore:
    

  comment: on-failure

dependency:
  files:
    - go.mod
